# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '光照度温度及湿度传感器工具软件.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(854, 703)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Modbus_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.Modbus_groupBox.setGeometry(QtCore.QRect(10, 10, 271, 61))
        self.Modbus_groupBox.setObjectName("Modbus_groupBox")
        self.Device_label = QtWidgets.QLabel(self.Modbus_groupBox)
        self.Device_label.setGeometry(QtCore.QRect(20, 20, 71, 31))
        self.Device_label.setObjectName("Device_label")
        self.Function_label = QtWidgets.QLabel(self.Modbus_groupBox)
        self.Function_label.setGeometry(QtCore.QRect(150, 20, 51, 31))
        self.Function_label.setObjectName("Function_label")
        self.Functiom_lineEdit = QtWidgets.QLineEdit(self.Modbus_groupBox)
        self.Functiom_lineEdit.setGeometry(QtCore.QRect(200, 20, 51, 31))
        self.Functiom_lineEdit.setObjectName("Functiom_lineEdit")
        self.Device_lineEdit = QtWidgets.QLineEdit(self.Modbus_groupBox)
        self.Device_lineEdit.setGeometry(QtCore.QRect(90, 20, 51, 31))
        self.Device_lineEdit.setObjectName("Device_lineEdit")
        self.Port_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.Port_groupBox.setGeometry(QtCore.QRect(10, 80, 271, 61))
        self.Port_groupBox.setObjectName("Port_groupBox")
        self.Port_label = QtWidgets.QLabel(self.Port_groupBox)
        self.Port_label.setGeometry(QtCore.QRect(10, 20, 61, 41))
        self.Port_label.setObjectName("Port_label")
        self.Port_comboBox = QtWidgets.QComboBox(self.Port_groupBox)
        self.Port_comboBox.setGeometry(QtCore.QRect(80, 30, 61, 21))
        self.Port_comboBox.setObjectName("Port_comboBox")
        self.Port_comboBox.addItem("")
        self.Port_comboBox.addItem("")
        self.Port_comboBox.addItem("")
        self.Port_comboBox.addItem("")
        self.Port_comboBox.addItem("")
        self.Port_comboBox.addItem("")
        self.Port_comboBox.addItem("")
        self.Baud_comboBox = QtWidgets.QComboBox(self.Port_groupBox)
        self.Baud_comboBox.setGeometry(QtCore.QRect(190, 30, 61, 22))
        self.Baud_comboBox.setObjectName("Baud_comboBox")
        self.Baud_comboBox.addItem("")
        self.Baud_comboBox.addItem("")
        self.Baud_comboBox.addItem("")
        self.Baud_label = QtWidgets.QLabel(self.Port_groupBox)
        self.Baud_label.setGeometry(QtCore.QRect(140, 20, 61, 41))
        self.Baud_label.setObjectName("Baud_label")
        self.Data_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.Data_groupBox.setGeometry(QtCore.QRect(300, 10, 391, 131))
        self.Data_groupBox.setObjectName("Data_groupBox")
        self.Time_lineEdit = QtWidgets.QLineEdit(self.Data_groupBox)
        self.Time_lineEdit.setGeometry(QtCore.QRect(120, 30, 51, 31))
        self.Time_lineEdit.setText("")
        self.Time_lineEdit.setObjectName("Time_lineEdit")
        self.Time_label = QtWidgets.QLabel(self.Data_groupBox)
        self.Time_label.setGeometry(QtCore.QRect(20, 30, 91, 31))
        self.Time_label.setObjectName("Time_label")
        self.Circle_pushButton = QtWidgets.QPushButton(self.Data_groupBox)
        self.Circle_pushButton.setGeometry(QtCore.QRect(270, 30, 75, 31))
        self.Circle_pushButton.setObjectName("Circle_pushButton")
        self.Signal_pushButton = QtWidgets.QPushButton(self.Data_groupBox)
        self.Signal_pushButton.setGeometry(QtCore.QRect(190, 30, 75, 31))
        self.Signal_pushButton.setObjectName("Signal_pushButton")
        self.Stop_pushButton = QtWidgets.QPushButton(self.Data_groupBox)
        self.Stop_pushButton.setGeometry(QtCore.QRect(270, 70, 75, 31))
        self.Stop_pushButton.setObjectName("Stop_pushButton")
        self.Close_pushButton = QtWidgets.QPushButton(self.Data_groupBox)
        self.Close_pushButton.setGeometry(QtCore.QRect(150, 70, 75, 31))
        self.Close_pushButton.setObjectName("Close_pushButton")
        self.Open_pushButton = QtWidgets.QPushButton(self.Data_groupBox)
        self.Open_pushButton.setGeometry(QtCore.QRect(20, 70, 75, 31))
        self.Open_pushButton.setObjectName("Open_pushButton")
        self.Command_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.Command_groupBox.setGeometry(QtCore.QRect(300, 150, 391, 201))
        self.Command_groupBox.setObjectName("Command_groupBox")
        self.Send_lineEdit = QtWidgets.QLineEdit(self.Command_groupBox)
        self.Send_lineEdit.setGeometry(QtCore.QRect(100, 80, 281, 31))
        self.Send_lineEdit.setText("")
        self.Send_lineEdit.setObjectName("Send_lineEdit")
        self.Recieve_label = QtWidgets.QLabel(self.Command_groupBox)
        self.Recieve_label.setGeometry(QtCore.QRect(20, 140, 61, 31))
        self.Recieve_label.setObjectName("Recieve_label")
        self.Recieve_plainTextEdit = QtWidgets.QPlainTextEdit(self.Command_groupBox)
        self.Recieve_plainTextEdit.setGeometry(QtCore.QRect(100, 120, 281, 71))
        self.Recieve_plainTextEdit.setObjectName("Recieve_plainTextEdit")
        self.Send_label = QtWidgets.QLabel(self.Command_groupBox)
        self.Send_label.setGeometry(QtCore.QRect(20, 80, 61, 31))
        self.Send_label.setObjectName("Send_label")
        self.State_label = QtWidgets.QLabel(self.Command_groupBox)
        self.State_label.setGeometry(QtCore.QRect(30, 30, 51, 31))
        self.State_label.setObjectName("State_label")
        self.Show_label = QtWidgets.QLabel(self.Command_groupBox)
        self.Show_label.setGeometry(QtCore.QRect(100, 30, 271, 41))
        self.Show_label.setText("")
        self.Show_label.setObjectName("Show_label")
        self.Watch_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.Watch_groupBox.setGeometry(QtCore.QRect(10, 150, 271, 201))
        self.Watch_groupBox.setObjectName("Watch_groupBox")
        self.C_label = QtWidgets.QLabel(self.Watch_groupBox)
        self.C_label.setGeometry(QtCore.QRect(190, 70, 31, 41))
        self.C_label.setObjectName("C_label")
        self.Temp_lineEdit = QtWidgets.QLineEdit(self.Watch_groupBox)
        self.Temp_lineEdit.setGeometry(QtCore.QRect(80, 70, 101, 31))
        self.Temp_lineEdit.setText("")
        self.Temp_lineEdit.setObjectName("Temp_lineEdit")
        self.Humidity_lineEdit = QtWidgets.QLineEdit(self.Watch_groupBox)
        self.Humidity_lineEdit.setGeometry(QtCore.QRect(80, 110, 101, 31))
        self.Humidity_lineEdit.setObjectName("Humidity_lineEdit")
        self.Temp_label = QtWidgets.QLabel(self.Watch_groupBox)
        self.Temp_label.setGeometry(QtCore.QRect(20, 70, 41, 31))
        self.Temp_label.setObjectName("Temp_label")
        self.Airspped_lineEdit = QtWidgets.QLineEdit(self.Watch_groupBox)
        self.Airspped_lineEdit.setGeometry(QtCore.QRect(80, 150, 101, 31))
        self.Airspped_lineEdit.setObjectName("Airspped_lineEdit")
        self.RH_label = QtWidgets.QLabel(self.Watch_groupBox)
        self.RH_label.setGeometry(QtCore.QRect(190, 111, 41, 31))
        self.RH_label.setObjectName("RH_label")
        self.illumation_label = QtWidgets.QLabel(self.Watch_groupBox)
        self.illumation_label.setGeometry(QtCore.QRect(20, 30, 51, 31))
        self.illumation_label.setObjectName("illumation_label")
        self.LX_label = QtWidgets.QLabel(self.Watch_groupBox)
        self.LX_label.setGeometry(QtCore.QRect(190, 30, 41, 31))
        self.LX_label.setObjectName("LX_label")
        self.MS_label = QtWidgets.QLabel(self.Watch_groupBox)
        self.MS_label.setGeometry(QtCore.QRect(190, 150, 31, 31))
        self.MS_label.setObjectName("MS_label")
        self.illumation_lineEdit = QtWidgets.QLineEdit(self.Watch_groupBox)
        self.illumation_lineEdit.setGeometry(QtCore.QRect(80, 30, 101, 31))
        self.illumation_lineEdit.setText("")
        self.illumation_lineEdit.setObjectName("illumation_lineEdit")
        self.Airspeed_label = QtWidgets.QLabel(self.Watch_groupBox)
        self.Airspeed_label.setGeometry(QtCore.QRect(20, 150, 41, 41))
        self.Airspeed_label.setObjectName("Airspeed_label")
        self.Humidity_label = QtWidgets.QLabel(self.Watch_groupBox)
        self.Humidity_label.setGeometry(QtCore.QRect(20, 110, 41, 41))
        self.Humidity_label.setObjectName("Humidity_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 854, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_2 = QtWidgets.QAction(MainWindow)
        self.actionSave_2.setObjectName("actionSave_2")
        self.menu.addAction(self.actionSave_2)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Modbus_groupBox.setTitle(_translate("MainWindow", "MODBUS设置"))
        self.Device_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">设备地址</span></p></body></html>"))
        self.Function_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">功能码</span></p></body></html>"))
        self.Port_groupBox.setTitle(_translate("MainWindow", "串口设置"))
        self.Port_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">串口设置</span></p></body></html>"))
        self.Port_comboBox.setItemText(0, _translate("MainWindow", "COM1"))
        self.Port_comboBox.setItemText(1, _translate("MainWindow", "COM2"))
        self.Port_comboBox.setItemText(2, _translate("MainWindow", "COM3"))
        self.Port_comboBox.setItemText(3, _translate("MainWindow", "COM4"))
        self.Port_comboBox.setItemText(4, _translate("MainWindow", "COM5"))
        self.Port_comboBox.setItemText(5, _translate("MainWindow", "COM6"))
        self.Port_comboBox.setItemText(6, _translate("MainWindow", "COM7"))
        self.Baud_comboBox.setItemText(0, _translate("MainWindow", "9600"))
        self.Baud_comboBox.setItemText(1, _translate("MainWindow", "14400"))
        self.Baud_comboBox.setItemText(2, _translate("MainWindow", "19200"))
        self.Baud_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">波特率</span></p></body></html>"))
        self.Data_groupBox.setTitle(_translate("MainWindow", "数据查询操作"))
        self.Time_lineEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">1000</span></p></body></html>"))
        self.Time_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">定时时长(ms)</span></p></body></html>"))
        self.Circle_pushButton.setText(_translate("MainWindow", "循环"))
        self.Signal_pushButton.setText(_translate("MainWindow", "单次"))
        self.Stop_pushButton.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">停止</span></p></body></html>"))
        self.Stop_pushButton.setText(_translate("MainWindow", "停止"))
        self.Close_pushButton.setText(_translate("MainWindow", "关闭"))
        self.Open_pushButton.setText(_translate("MainWindow", "打开"))
        self.Command_groupBox.setTitle(_translate("MainWindow", "命令观察窗口"))
        self.Recieve_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">接收命令</span></p></body></html>"))
        self.Send_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">发送命令</span></p></body></html>"))
        self.State_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">状  态</span></p></body></html>"))
        self.Watch_groupBox.setTitle(_translate("MainWindow", "观察窗口"))
        self.C_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">℃</span></p></body></html>"))
        self.Temp_lineEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.Temp_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">温 度 </span></p></body></html>"))
        self.RH_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">%RH</span></p></body></html>"))
        self.illumation_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">光照度</span></p></body></html>"))
        self.LX_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">LX</span></p></body></html>"))
        self.MS_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">m/s</span></p></body></html>"))
        self.illumation_lineEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">0.00</span></p></body></html>"))
        self.Airspeed_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">风 速</span></p></body></html>"))
        self.Humidity_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">湿 度</span></p></body></html>"))
        self.menu.setTitle(_translate("MainWindow", "设置"))
        self.actionSave.setText(_translate("MainWindow", "save"))
        self.actionSave_2.setText(_translate("MainWindow", "save"))

